name: GitHub Stats

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create profile folder
        run: mkdir -p profile

      - name: Download stats card
        run: |
          curl -L -o profile/stats.svg "https://github-readme-stats.vercel.app/api?username=AhsanBaidar&show_icons=true&theme=dark"

      - name: Commit files
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add profile/stats.svg
          git commit -m "Update stats" || echo "No changes"
          git push
